dist: trusty
language: java
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
jdk:
  - oraclejdk8
install: true
script: mvn -B -nsu verify
cache:
  directories:
    - $HOME/.m2
branches:
  except:
  - /^release\/.*$/
